services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=coupon'
      - 'MONGO_INITDB_ROOT_USERNAME=user'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
    ports:
      - '27017:27017'
    volumes:
      - "coupons_database:/data/db"
volumes:
  coupons_database:
